name: app_idx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.3.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  provider: 6.1.2 
  go_router: ^14.2.1
  link_embeder: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/arduinouno_image.png
    - assets/images/arduinonano_image.png
    - assets/images/arduinomega_image.png
    - assets/images/esp_image.png
