// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQYVCnEr8xkSsJukTolZPLPP3EM2mTFtI',
    appId: '1:872915492795:web:0ba561057411dc9adf6e9e',
    messagingSenderId: '872915492795',
    projectId: 'fir-example-ca8d7',
    authDomain: 'fir-example-ca8d7.firebaseapp.com',
    storageBucket: 'fir-example-ca8d7.appspot.com',
    measurementId: 'G-1SGC770WH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIgmRo7MVggj3Ili5OCpnX3StEWRmlHc',
    appId: '1:872915492795:android:fd00a2ebe0ee9df5df6e9e',
    messagingSenderId: '872915492795',
    projectId: 'fir-example-ca8d7',
    storageBucket: 'fir-example-ca8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROCLG33QwTOM9T_pbONZRMKfHhN_As7s',
    appId: '1:872915492795:ios:08a6c5b45289ff40df6e9e',
    messagingSenderId: '872915492795',
    projectId: 'fir-example-ca8d7',
    storageBucket: 'fir-example-ca8d7.appspot.com',
    iosClientId: '872915492795-sg4lb11o367qqqq2t2lk3f7gr6pbt6pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAROCLG33QwTOM9T_pbONZRMKfHhN_As7s',
    appId: '1:872915492795:ios:08a6c5b45289ff40df6e9e',
    messagingSenderId: '872915492795',
    projectId: 'fir-example-ca8d7',
    storageBucket: 'fir-example-ca8d7.appspot.com',
    iosClientId: '872915492795-sg4lb11o367qqqq2t2lk3f7gr6pbt6pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQYVCnEr8xkSsJukTolZPLPP3EM2mTFtI',
    appId: '1:872915492795:web:97ef1337cf372ecddf6e9e',
    messagingSenderId: '872915492795',
    projectId: 'fir-example-ca8d7',
    authDomain: 'fir-example-ca8d7.firebaseapp.com',
    storageBucket: 'fir-example-ca8d7.appspot.com',
    measurementId: 'G-TVYJD508QH',
  );

}